"""schema inicial: tabelas existentes + tenant/user/auth + buyerradar

Revision ID: 0829846b894e
Revises: 
Create Date: 2026-07-14 19:17:03.448216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0829846b894e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_entries_tenant_id'), 'audit_log_entries', ['tenant_id'], unique=False)
    op.create_table('bot_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('input_original', sa.String(length=500), nullable=False),
    sa.Column('tipo_identificado', sa.String(length=50), nullable=False),
    sa.Column('objetivo', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resumo_humano', sa.Text(), nullable=True),
    sa.Column('proxima_acao', sa.Text(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_jobs_id'), 'bot_jobs', ['id'], unique=False)
    op.create_table('bot_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('bot_name', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('resultado', sa.JSON(), nullable=True),
    sa.Column('warning', sa.Text(), nullable=True),
    sa.Column('erro', sa.Text(), nullable=True),
    sa.Column('evidence_id', sa.Integer(), nullable=True),
    sa.Column('next_action', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_steps_id'), 'bot_steps', ['id'], unique=False)
    op.create_index(op.f('ix_bot_steps_job_id'), 'bot_steps', ['job_id'], unique=False)
    op.create_table('certificate_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('source_id', sa.String(length=80), nullable=False),
    sa.Column('certificate_type', sa.String(length=50), nullable=False),
    sa.Column('document_masked', sa.String(length=50), nullable=True),
    sa.Column('name_consulted', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=60), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('validation_code', sa.String(length=255), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('fonte_url', sa.String(length=500), nullable=True),
    sa.Column('issued_at', sa.String(length=50), nullable=True),
    sa.Column('valid_until', sa.String(length=50), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certificate_records_id'), 'certificate_records', ['id'], unique=False)
    op.create_index(op.f('ix_certificate_records_source_id'), 'certificate_records', ['source_id'], unique=False)
    op.create_table('diligencia_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('input_original', sa.String(length=500), nullable=False),
    sa.Column('tipo_identificado', sa.String(length=50), nullable=False),
    sa.Column('valor_normalizado', sa.String(length=500), nullable=False),
    sa.Column('objetivo', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('resumo_humano', sa.Text(), nullable=True),
    sa.Column('proxima_acao_recomendada', sa.Text(), nullable=True),
    sa.Column('resultados_confirmados', sa.JSON(), nullable=True),
    sa.Column('indicios', sa.JSON(), nullable=True),
    sa.Column('pendencias', sa.JSON(), nullable=True),
    sa.Column('fontes_manuais_recomendadas', sa.JSON(), nullable=True),
    sa.Column('raw_avancado', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diligencia_logs_id'), 'diligencia_logs', ['id'], unique=False)
    op.create_table('intake_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('input_original', sa.Text(), nullable=False),
    sa.Column('dados_extraidos', sa.JSON(), nullable=True),
    sa.Column('processos_detectados', sa.JSON(), nullable=True),
    sa.Column('divergencias', sa.JSON(), nullable=True),
    sa.Column('dados_faltantes', sa.JSON(), nullable=True),
    sa.Column('resposta_sugerida', sa.Text(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('job_id_referencia', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intake_cases_id'), 'intake_cases', ['id'], unique=False)
    op.create_index(op.f('ix_intake_cases_lead_id'), 'intake_cases', ['lead_id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('telefone', sa.String(length=30), nullable=True),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('cpf', sa.String(length=20), nullable=True),
    sa.Column('cnpj', sa.String(length=20), nullable=True),
    sa.Column('origem', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_table('manual_evidences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('fonte', sa.String(length=255), nullable=False),
    sa.Column('referencia', sa.String(length=255), nullable=True),
    sa.Column('texto', sa.Text(), nullable=True),
    sa.Column('arquivo_nome', sa.String(length=255), nullable=True),
    sa.Column('arquivo_caminho', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manual_evidences_id'), 'manual_evidences', ['id'], unique=False)
    op.create_table('opportunity_leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=200), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('seen_count', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('process_number', sa.String(length=40), nullable=True),
    sa.Column('normalized_cnj', sa.String(length=20), nullable=True),
    sa.Column('tribunal', sa.String(length=20), nullable=True),
    sa.Column('segment', sa.String(length=50), nullable=True),
    sa.Column('uf', sa.String(length=5), nullable=True),
    sa.Column('debtor', sa.String(length=255), nullable=True),
    sa.Column('creditor_name', sa.String(length=255), nullable=True),
    sa.Column('creditor_document_masked', sa.String(length=20), nullable=True),
    sa.Column('creditor_document_hash', sa.String(length=64), nullable=True),
    sa.Column('lawyer_name', sa.String(length=255), nullable=True),
    sa.Column('signal_type', sa.String(length=30), nullable=True),
    sa.Column('phase', sa.String(length=50), nullable=True),
    sa.Column('estimated_opportunity_type', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('bot_job_id', sa.Integer(), nullable=True),
    sa.Column('dossie_url', sa.String(length=200), nullable=True),
    sa.Column('next_action', sa.Text(), nullable=True),
    sa.Column('publication_text', sa.Text(), nullable=True),
    sa.Column('matched_terms', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunity_leads_creditor_document_hash'), 'opportunity_leads', ['creditor_document_hash'], unique=False)
    op.create_index(op.f('ix_opportunity_leads_dedupe_key'), 'opportunity_leads', ['dedupe_key'], unique=False)
    op.create_index(op.f('ix_opportunity_leads_id'), 'opportunity_leads', ['id'], unique=False)
    op.create_table('process_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_log_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('tribunal', sa.String(length=50), nullable=True),
    sa.Column('numero_processo', sa.String(length=50), nullable=True),
    sa.Column('classe', sa.String(length=255), nullable=True),
    sa.Column('assunto', sa.Text(), nullable=True),
    sa.Column('orgao_julgador', sa.Text(), nullable=True),
    sa.Column('data_ajuizamento', sa.String(length=50), nullable=True),
    sa.Column('ultima_atualizacao', sa.String(length=50), nullable=True),
    sa.Column('precatorio_score', sa.Integer(), nullable=False),
    sa.Column('precatorio_flags', sa.JSON(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_process_results_id'), 'process_results', ['id'], unique=False)
    op.create_index(op.f('ix_process_results_numero_processo'), 'process_results', ['numero_processo'], unique=False)
    op.create_index(op.f('ix_process_results_search_log_id'), 'process_results', ['search_log_id'], unique=False)
    op.create_table('publication_hits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watcher_run_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('tribunal', sa.String(length=20), nullable=True),
    sa.Column('publication_date', sa.String(length=20), nullable=True),
    sa.Column('process_number', sa.String(length=40), nullable=True),
    sa.Column('normalized_cnj', sa.String(length=20), nullable=True),
    sa.Column('parties_text', sa.Text(), nullable=True),
    sa.Column('lawyers_text', sa.Text(), nullable=True),
    sa.Column('publication_text', sa.Text(), nullable=True),
    sa.Column('text_hash', sa.String(length=64), nullable=True),
    sa.Column('matched_terms', sa.JSON(), nullable=True),
    sa.Column('signal_type', sa.String(length=30), nullable=True),
    sa.Column('confidence', sa.String(length=10), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publication_hits_id'), 'publication_hits', ['id'], unique=False)
    op.create_index(op.f('ix_publication_hits_text_hash'), 'publication_hits', ['text_hash'], unique=False)
    op.create_index(op.f('ix_publication_hits_watcher_run_id'), 'publication_hits', ['watcher_run_id'], unique=False)
    op.create_table('search_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('search_type', sa.String(length=50), nullable=False),
    sa.Column('search_key_masked', sa.String(length=255), nullable=False),
    sa.Column('tribunals', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('raw_request', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_logs_id'), 'search_logs', ['id'], unique=False)
    op.create_table('stj_official_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('natureza', sa.String(length=50), nullable=True),
    sa.Column('entidade_devedora', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('local_path', sa.String(length=500), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stj_official_files_id'), 'stj_official_files', ['id'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('watcher_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watcher_name', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('date_from', sa.String(length=20), nullable=True),
    sa.Column('date_to', sa.String(length=20), nullable=True),
    sa.Column('tribunals_scanned', sa.JSON(), nullable=True),
    sa.Column('total_publications', sa.Integer(), nullable=False),
    sa.Column('total_matches', sa.Integer(), nullable=False),
    sa.Column('total_leads_created', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watcher_runs_id'), 'watcher_runs', ['id'], unique=False)
    op.create_table('whatsapp_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('telefone', sa.String(length=30), nullable=True),
    sa.Column('texto_original', sa.Text(), nullable=True),
    sa.Column('arquivo_evidencia', sa.String(length=500), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_messages_id'), 'whatsapp_messages', ['id'], unique=False)
    op.create_index(op.f('ix_whatsapp_messages_lead_id'), 'whatsapp_messages', ['lead_id'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=True),
    sa.Column('role', sa.Enum('GESTORA', 'ADMINISTRADORA', 'CUSTODIANTE', 'AUDITOR', 'CONTROLADOR', 'BANCO', 'FAMILY_OFFICE', 'SECURITIZADORA', 'ESCRITORIO_ADVOCACIA', 'OUTRO', name='orgrole', native_enum=False, length=30), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_cnpj'), 'organizations', ['cnpj'], unique=False)
    op.create_index(op.f('ix_organizations_legal_name'), 'organizations', ['legal_name'], unique=False)
    op.create_index(op.f('ix_organizations_tenant_id'), 'organizations', ['tenant_id'], unique=False)
    op.create_table('suppression_list',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.Enum('BOUNCE', 'RECLAMACAO', 'DESCADASTRO', 'MANUAL', name='suppressionreason', native_enum=False, length=20), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_suppression_tenant_email')
    )
    op.create_index(op.f('ix_suppression_list_email'), 'suppression_list', ['email'], unique=False)
    op.create_index(op.f('ix_suppression_list_tenant_id'), 'suppression_list', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMINISTRADOR', 'PESQUISADOR', 'JURIDICO', 'COMERCIAL', 'APROVADOR', 'VISUALIZADOR', name='userrole', native_enum=False, length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_user_tenant_email')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('buyer_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('classification', sa.Enum('COMPRADOR_PRINCIPAL', 'GESTOR_MANDATO_COMPRADOR', 'INTERMEDIARIO_ORIGINADOR', 'ADMINISTRADOR_CUSTODIANTE', name='buyerclassification', native_enum=False, length=40), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('campaign_eligible', sa.Boolean(), nullable=False),
    sa.Column('ticket_min', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('ticket_max', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('ticket_confidence', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buyer_profiles_organization_id'), 'buyer_profiles', ['organization_id'], unique=False)
    op.create_index(op.f('ix_buyer_profiles_tenant_id'), 'buyer_profiles', ['tenant_id'], unique=False)
    op.create_table('funds',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('cnpj', sa.String(length=18), nullable=False),
    sa.Column('cd_cvm', sa.String(length=10), nullable=True),
    sa.Column('denom_social', sa.String(length=255), nullable=False),
    sa.Column('classe', sa.String(length=120), nullable=True),
    sa.Column('situacao', sa.String(length=120), nullable=True),
    sa.Column('patrimonio_liquido', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('dt_patrimonio_liquido', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funds_cd_cvm'), 'funds', ['cd_cvm'], unique=False)
    op.create_index(op.f('ix_funds_cnpj'), 'funds', ['cnpj'], unique=False)
    op.create_index(op.f('ix_funds_denom_social'), 'funds', ['denom_social'], unique=False)
    op.create_index(op.f('ix_funds_organization_id'), 'funds', ['organization_id'], unique=False)
    op.create_index(op.f('ix_funds_tenant_id'), 'funds', ['tenant_id'], unique=False)
    op.create_table('people',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role_title', sa.String(length=255), nullable=True),
    sa.Column('is_priority_role', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_people_organization_id'), 'people', ['organization_id'], unique=False)
    op.create_index(op.f('ix_people_tenant_id'), 'people', ['tenant_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_token_hash'), 'user_sessions', ['token_hash'], unique=False)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('buyer_mandates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('buyer_profile_id', sa.String(length=36), nullable=False),
    sa.Column('asset_type', sa.Enum('RPV', 'PRECATORIO', 'DIREITO_CREDITORIO', name='assettype', native_enum=False, length=30), nullable=True),
    sa.Column('sphere', sa.Enum('FEDERAL', 'ESTADUAL', 'MUNICIPAL', 'DISTRITAL', 'PRIVADA', name='assetsphere', native_enum=False, length=20), nullable=True),
    sa.Column('nature', sa.Enum('ALIMENTAR', 'COMUM', 'TRABALHISTA', 'TRIBUTARIA', 'CIVEL', name='assetnature', native_enum=False, length=20), nullable=True),
    sa.Column('value_min', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('value_max', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('max_expected_months', sa.Integer(), nullable=True),
    sa.Column('accepts_partial_cession', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_profile_id'], ['buyer_profiles.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buyer_mandates_buyer_profile_id'), 'buyer_mandates', ['buyer_profile_id'], unique=False)
    op.create_index(op.f('ix_buyer_mandates_tenant_id'), 'buyer_mandates', ['tenant_id'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('email_status', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('do_not_contact', sa.Boolean(), nullable=False),
    sa.Column('contact_ready_for_campaign', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_person_id'), 'contacts', ['person_id'], unique=True)
    op.create_index(op.f('ix_contacts_tenant_id'), 'contacts', ['tenant_id'], unique=False)
    op.create_table('judicial_opportunities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=True),
    sa.Column('source_opportunity_lead_id', sa.Integer(), nullable=True),
    sa.Column('opportunity_name', sa.String(length=255), nullable=True),
    sa.Column('asset_type', sa.Enum('RPV', 'PRECATORIO', 'DIREITO_CREDITORIO', name='assettype', native_enum=False, length=30), nullable=True),
    sa.Column('judicial_sphere', sa.Enum('FEDERAL', 'ESTADUAL', 'MUNICIPAL', 'DISTRITAL', 'PRIVADA', name='assetsphere', native_enum=False, length=20), nullable=True),
    sa.Column('credit_nature', sa.Enum('ALIMENTAR', 'COMUM', 'TRABALHISTA', 'TRIBUTARIA', 'CIVEL', name='assetnature', native_enum=False, length=20), nullable=True),
    sa.Column('court', sa.String(length=20), nullable=True),
    sa.Column('judicial_unit', sa.String(length=255), nullable=True),
    sa.Column('debtor', sa.String(length=255), nullable=True),
    sa.Column('process_number', sa.String(length=40), nullable=True),
    sa.Column('requisition_number', sa.String(length=60), nullable=True),
    sa.Column('face_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('updated_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('expected_net_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('seller_asking_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('intended_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('final_judgment_status', sa.String(length=50), nullable=True),
    sa.Column('liquidation_status', sa.String(length=50), nullable=True),
    sa.Column('enforcement_status', sa.String(length=50), nullable=True),
    sa.Column('requisition_status', sa.String(length=50), nullable=True),
    sa.Column('budget_year', sa.Integer(), nullable=True),
    sa.Column('expected_payment_date', sa.Date(), nullable=True),
    sa.Column('legal_risk_level', sa.String(length=20), nullable=True),
    sa.Column('acquisition_eligibility', sa.String(length=30), nullable=True),
    sa.Column('acquisition_blockers', sa.JSON(), nullable=True),
    sa.Column('source_confidence', sa.String(length=20), nullable=True),
    sa.Column('validation_status', sa.String(length=30), nullable=False),
    sa.Column('pipeline_status', sa.Enum('PROCESSO_ENCONTRADO', 'POSSIVEL_CREDITO', 'ANALISE_AUTOMATICA', 'VALIDACAO_JURIDICA', 'ATIVO_QUALIFICADO', 'COMPRADORES_IDENTIFICADOS', 'TEASER_APROVADO', 'DISTRIBUIDO', 'INTERESSADO', 'EM_DILIGENCIA', 'PROPOSTA_RECEBIDA', 'NEGOCIACAO', 'AQUISICAO_CONCLUIDA', 'SEM_ATIVO', 'DESCARTADO', name='opportunitypipelinestatus', native_enum=False, length=30), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_judicial_opportunities_process_number'), 'judicial_opportunities', ['process_number'], unique=False)
    op.create_index(op.f('ix_judicial_opportunities_tenant_id'), 'judicial_opportunities', ['tenant_id'], unique=False)
    op.create_table('buyer_asset_matches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('opportunity_id', sa.String(length=36), nullable=False),
    sa.Column('buyer_profile_id', sa.String(length=36), nullable=False),
    sa.Column('compatibility_score', sa.Integer(), nullable=False),
    sa.Column('evaluated_weight', sa.Integer(), nullable=False),
    sa.Column('positive_reasons', sa.JSON(), nullable=True),
    sa.Column('negative_reasons', sa.JSON(), nullable=True),
    sa.Column('unverified_criteria', sa.JSON(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_profile_id'], ['buyer_profiles.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['judicial_opportunities.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opportunity_id', 'buyer_profile_id', name='uq_opportunity_buyer')
    )
    op.create_index(op.f('ix_buyer_asset_matches_buyer_profile_id'), 'buyer_asset_matches', ['buyer_profile_id'], unique=False)
    op.create_index(op.f('ix_buyer_asset_matches_opportunity_id'), 'buyer_asset_matches', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_buyer_asset_matches_tenant_id'), 'buyer_asset_matches', ['tenant_id'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('opportunity_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('RASCUNHO', 'PRONTA_PARA_REVISAO', 'APROVADA', 'ENVIANDO', 'CONCLUIDA', 'CANCELADA', name='campaignstatus', native_enum=False, length=30), nullable=False),
    sa.Column('teaser_text', sa.Text(), nullable=True),
    sa.Column('asking_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('asking_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('approved_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['judicial_opportunities.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_opportunity_id'), 'campaigns', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_campaigns_tenant_id'), 'campaigns', ['tenant_id'], unique=False)
    op.create_table('opportunity_field_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('opportunity_id', sa.String(length=36), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('source_excerpt', sa.Text(), nullable=True),
    sa.Column('source_document', sa.String(length=255), nullable=True),
    sa.Column('source_date', sa.Date(), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=True),
    sa.Column('extraction_method', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['judicial_opportunities.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunity_field_sources_opportunity_id'), 'opportunity_field_sources', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_opportunity_field_sources_tenant_id'), 'opportunity_field_sources', ['tenant_id'], unique=False)
    op.create_table('buyer_proposals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('opportunity_id', sa.String(length=36), nullable=False),
    sa.Column('buyer_profile_id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=True),
    sa.Column('proposal_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('proposal_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('asset_fraction', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('payment_terms', sa.Text(), nullable=True),
    sa.Column('conditions_precedent', sa.Text(), nullable=True),
    sa.Column('due_diligence_requirements', sa.Text(), nullable=True),
    sa.Column('exclusivity_requested', sa.Boolean(), nullable=False),
    sa.Column('proposal_expiration', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('RECEBIDA', 'EM_ANALISE', 'ACEITA', 'RECUSADA', 'EXPIRADA', 'RETIRADA', name='proposalstatus', native_enum=False, length=20), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('source_message_id', sa.String(length=255), nullable=True),
    sa.Column('entered_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_profile_id'], ['buyer_profiles.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['judicial_opportunities.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buyer_proposals_buyer_profile_id'), 'buyer_proposals', ['buyer_profile_id'], unique=False)
    op.create_index(op.f('ix_buyer_proposals_opportunity_id'), 'buyer_proposals', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_buyer_proposals_tenant_id'), 'buyer_proposals', ['tenant_id'], unique=False)
    op.create_table('campaign_recipients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('buyer_profile_id', sa.String(length=36), nullable=False),
    sa.Column('contact_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('RASCUNHO', 'PRONTO', 'ENVIADO', 'ENTREGUE', 'ABERTO', 'CLICADO', 'RESPONDIDO', 'BOUNCE', 'RECLAMACAO', 'DESCADASTRADO', 'ERRO', 'SUSPENSO', name='recipientstatus', native_enum=False, length=20), nullable=False),
    sa.Column('rendered_subject', sa.String(length=255), nullable=True),
    sa.Column('rendered_body', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_profile_id'], ['buyer_profiles.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_recipients_buyer_profile_id'), 'campaign_recipients', ['buyer_profile_id'], unique=False)
    op.create_index(op.f('ix_campaign_recipients_campaign_id'), 'campaign_recipients', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_recipients_tenant_id'), 'campaign_recipients', ['tenant_id'], unique=False)
    op.create_table('outbound_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_recipient_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['campaign_recipient_id'], ['campaign_recipients.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_outbound_messages_campaign_recipient_id'), 'outbound_messages', ['campaign_recipient_id'], unique=False)
    op.create_index(op.f('ix_outbound_messages_tenant_id'), 'outbound_messages', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outbound_messages_tenant_id'), table_name='outbound_messages')
    op.drop_index(op.f('ix_outbound_messages_campaign_recipient_id'), table_name='outbound_messages')
    op.drop_table('outbound_messages')
    op.drop_index(op.f('ix_campaign_recipients_tenant_id'), table_name='campaign_recipients')
    op.drop_index(op.f('ix_campaign_recipients_campaign_id'), table_name='campaign_recipients')
    op.drop_index(op.f('ix_campaign_recipients_buyer_profile_id'), table_name='campaign_recipients')
    op.drop_table('campaign_recipients')
    op.drop_index(op.f('ix_buyer_proposals_tenant_id'), table_name='buyer_proposals')
    op.drop_index(op.f('ix_buyer_proposals_opportunity_id'), table_name='buyer_proposals')
    op.drop_index(op.f('ix_buyer_proposals_buyer_profile_id'), table_name='buyer_proposals')
    op.drop_table('buyer_proposals')
    op.drop_index(op.f('ix_opportunity_field_sources_tenant_id'), table_name='opportunity_field_sources')
    op.drop_index(op.f('ix_opportunity_field_sources_opportunity_id'), table_name='opportunity_field_sources')
    op.drop_table('opportunity_field_sources')
    op.drop_index(op.f('ix_campaigns_tenant_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_opportunity_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_buyer_asset_matches_tenant_id'), table_name='buyer_asset_matches')
    op.drop_index(op.f('ix_buyer_asset_matches_opportunity_id'), table_name='buyer_asset_matches')
    op.drop_index(op.f('ix_buyer_asset_matches_buyer_profile_id'), table_name='buyer_asset_matches')
    op.drop_table('buyer_asset_matches')
    op.drop_index(op.f('ix_judicial_opportunities_tenant_id'), table_name='judicial_opportunities')
    op.drop_index(op.f('ix_judicial_opportunities_process_number'), table_name='judicial_opportunities')
    op.drop_table('judicial_opportunities')
    op.drop_index(op.f('ix_contacts_tenant_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_person_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_buyer_mandates_tenant_id'), table_name='buyer_mandates')
    op.drop_index(op.f('ix_buyer_mandates_buyer_profile_id'), table_name='buyer_mandates')
    op.drop_table('buyer_mandates')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_token_hash'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_people_tenant_id'), table_name='people')
    op.drop_index(op.f('ix_people_organization_id'), table_name='people')
    op.drop_table('people')
    op.drop_index(op.f('ix_funds_tenant_id'), table_name='funds')
    op.drop_index(op.f('ix_funds_organization_id'), table_name='funds')
    op.drop_index(op.f('ix_funds_denom_social'), table_name='funds')
    op.drop_index(op.f('ix_funds_cnpj'), table_name='funds')
    op.drop_index(op.f('ix_funds_cd_cvm'), table_name='funds')
    op.drop_table('funds')
    op.drop_index(op.f('ix_buyer_profiles_tenant_id'), table_name='buyer_profiles')
    op.drop_index(op.f('ix_buyer_profiles_organization_id'), table_name='buyer_profiles')
    op.drop_table('buyer_profiles')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_suppression_list_tenant_id'), table_name='suppression_list')
    op.drop_index(op.f('ix_suppression_list_email'), table_name='suppression_list')
    op.drop_table('suppression_list')
    op.drop_index(op.f('ix_organizations_tenant_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_legal_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_cnpj'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_whatsapp_messages_lead_id'), table_name='whatsapp_messages')
    op.drop_index(op.f('ix_whatsapp_messages_id'), table_name='whatsapp_messages')
    op.drop_table('whatsapp_messages')
    op.drop_index(op.f('ix_watcher_runs_id'), table_name='watcher_runs')
    op.drop_table('watcher_runs')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_stj_official_files_id'), table_name='stj_official_files')
    op.drop_table('stj_official_files')
    op.drop_index(op.f('ix_search_logs_id'), table_name='search_logs')
    op.drop_table('search_logs')
    op.drop_index(op.f('ix_publication_hits_watcher_run_id'), table_name='publication_hits')
    op.drop_index(op.f('ix_publication_hits_text_hash'), table_name='publication_hits')
    op.drop_index(op.f('ix_publication_hits_id'), table_name='publication_hits')
    op.drop_table('publication_hits')
    op.drop_index(op.f('ix_process_results_search_log_id'), table_name='process_results')
    op.drop_index(op.f('ix_process_results_numero_processo'), table_name='process_results')
    op.drop_index(op.f('ix_process_results_id'), table_name='process_results')
    op.drop_table('process_results')
    op.drop_index(op.f('ix_opportunity_leads_id'), table_name='opportunity_leads')
    op.drop_index(op.f('ix_opportunity_leads_dedupe_key'), table_name='opportunity_leads')
    op.drop_index(op.f('ix_opportunity_leads_creditor_document_hash'), table_name='opportunity_leads')
    op.drop_table('opportunity_leads')
    op.drop_index(op.f('ix_manual_evidences_id'), table_name='manual_evidences')
    op.drop_table('manual_evidences')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_intake_cases_lead_id'), table_name='intake_cases')
    op.drop_index(op.f('ix_intake_cases_id'), table_name='intake_cases')
    op.drop_table('intake_cases')
    op.drop_index(op.f('ix_diligencia_logs_id'), table_name='diligencia_logs')
    op.drop_table('diligencia_logs')
    op.drop_index(op.f('ix_certificate_records_source_id'), table_name='certificate_records')
    op.drop_index(op.f('ix_certificate_records_id'), table_name='certificate_records')
    op.drop_table('certificate_records')
    op.drop_index(op.f('ix_bot_steps_job_id'), table_name='bot_steps')
    op.drop_index(op.f('ix_bot_steps_id'), table_name='bot_steps')
    op.drop_table('bot_steps')
    op.drop_index(op.f('ix_bot_jobs_id'), table_name='bot_jobs')
    op.drop_table('bot_jobs')
    op.drop_index(op.f('ix_audit_log_entries_tenant_id'), table_name='audit_log_entries')
    op.drop_table('audit_log_entries')
    # ### end Alembic commands ###
