"""v36 incremental tenant user auth buyerradar tenant_id

Revision ID: b05906fcd311
Revises: 605e28a0a5b4
Create Date: 2026-07-16 10:53:03.792234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b05906fcd311'
down_revision: Union[str, None] = '605e28a0a5b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_entries_tenant_id'), 'audit_log_entries', ['tenant_id'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=True),
    sa.Column('role', sa.Enum('GESTORA', 'ADMINISTRADORA', 'CUSTODIANTE', 'AUDITOR', 'CONTROLADOR', 'BANCO', 'FAMILY_OFFICE', 'SECURITIZADORA', 'ESCRITORIO_ADVOCACIA', 'OUTRO', name='orgrole', native_enum=False, length=30), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_cnpj'), 'organizations', ['cnpj'], unique=False)
    op.create_index(op.f('ix_organizations_legal_name'), 'organizations', ['legal_name'], unique=False)
    op.create_index(op.f('ix_organizations_tenant_id'), 'organizations', ['tenant_id'], unique=False)
    op.create_table('suppression_list',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.Enum('BOUNCE', 'RECLAMACAO', 'DESCADASTRO', 'MANUAL', name='suppressionreason', native_enum=False, length=20), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_suppression_tenant_email')
    )
    op.create_index(op.f('ix_suppression_list_email'), 'suppression_list', ['email'], unique=False)
    op.create_index(op.f('ix_suppression_list_tenant_id'), 'suppression_list', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMINISTRADOR', 'PESQUISADOR', 'JURIDICO', 'COMERCIAL', 'APROVADOR', 'VISUALIZADOR', name='userrole', native_enum=False, length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_user_tenant_email')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('buyer_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('classification', sa.Enum('COMPRADOR_PRINCIPAL', 'GESTOR_MANDATO_COMPRADOR', 'INTERMEDIARIO_ORIGINADOR', 'ADMINISTRADOR_CUSTODIANTE', name='buyerclassification', native_enum=False, length=40), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('campaign_eligible', sa.Boolean(), nullable=False),
    sa.Column('ticket_min', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('ticket_max', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('ticket_confidence', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buyer_profiles_organization_id'), 'buyer_profiles', ['organization_id'], unique=False)
    op.create_index(op.f('ix_buyer_profiles_tenant_id'), 'buyer_profiles', ['tenant_id'], unique=False)
    op.create_table('funds',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('cnpj', sa.String(length=18), nullable=False),
    sa.Column('cd_cvm', sa.String(length=10), nullable=True),
    sa.Column('denom_social', sa.String(length=255), nullable=False),
    sa.Column('classe', sa.String(length=120), nullable=True),
    sa.Column('situacao', sa.String(length=120), nullable=True),
    sa.Column('patrimonio_liquido', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('dt_patrimonio_liquido', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funds_cd_cvm'), 'funds', ['cd_cvm'], unique=False)
    op.create_index(op.f('ix_funds_cnpj'), 'funds', ['cnpj'], unique=False)
    op.create_index(op.f('ix_funds_denom_social'), 'funds', ['denom_social'], unique=False)
    op.create_index(op.f('ix_funds_organization_id'), 'funds', ['organization_id'], unique=False)
    op.create_index(op.f('ix_funds_tenant_id'), 'funds', ['tenant_id'], unique=False)
    op.create_table('people',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role_title', sa.String(length=255), nullable=True),
    sa.Column('is_priority_role', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_people_organization_id'), 'people', ['organization_id'], unique=False)
    op.create_index(op.f('ix_people_tenant_id'), 'people', ['tenant_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_token_hash'), 'user_sessions', ['token_hash'], unique=False)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('buyer_mandates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('buyer_profile_id', sa.String(length=36), nullable=False),
    sa.Column('asset_type', sa.Enum('RPV', 'PRECATORIO', 'DIREITO_CREDITORIO', name='assettype', native_enum=False, length=30), nullable=True),
    sa.Column('sphere', sa.Enum('FEDERAL', 'ESTADUAL', 'MUNICIPAL', 'DISTRITAL', 'PRIVADA', name='assetsphere', native_enum=False, length=20), nullable=True),
    sa.Column('nature', sa.Enum('ALIMENTAR', 'COMUM', 'TRABALHISTA', 'TRIBUTARIA', 'CIVEL', name='assetnature', native_enum=False, length=20), nullable=True),
    sa.Column('value_min', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('value_max', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('max_expected_months', sa.Integer(), nullable=True),
    sa.Column('accepts_partial_cession', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_profile_id'], ['buyer_profiles.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buyer_mandates_buyer_profile_id'), 'buyer_mandates', ['buyer_profile_id'], unique=False)
    op.create_index(op.f('ix_buyer_mandates_tenant_id'), 'buyer_mandates', ['tenant_id'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('email_status', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('do_not_contact', sa.Boolean(), nullable=False),
    sa.Column('contact_ready_for_campaign', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_person_id'), 'contacts', ['person_id'], unique=True)
    op.create_index(op.f('ix_contacts_tenant_id'), 'contacts', ['tenant_id'], unique=False)
    op.create_table('judicial_opportunities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=True),
    sa.Column('source_opportunity_lead_id', sa.Integer(), nullable=True),
    sa.Column('opportunity_name', sa.String(length=255), nullable=True),
    sa.Column('asset_type', sa.Enum('RPV', 'PRECATORIO', 'DIREITO_CREDITORIO', name='assettype', native_enum=False, length=30), nullable=True),
    sa.Column('judicial_sphere', sa.Enum('FEDERAL', 'ESTADUAL', 'MUNICIPAL', 'DISTRITAL', 'PRIVADA', name='assetsphere', native_enum=False, length=20), nullable=True),
    sa.Column('credit_nature', sa.Enum('ALIMENTAR', 'COMUM', 'TRABALHISTA', 'TRIBUTARIA', 'CIVEL', name='assetnature', native_enum=False, length=20), nullable=True),
    sa.Column('court', sa.String(length=20), nullable=True),
    sa.Column('judicial_unit', sa.String(length=255), nullable=True),
    sa.Column('debtor', sa.String(length=255), nullable=True),
    sa.Column('process_number', sa.String(length=40), nullable=True),
    sa.Column('requisition_number', sa.String(length=60), nullable=True),
    sa.Column('face_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('updated_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('expected_net_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('seller_asking_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('intended_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('final_judgment_status', sa.String(length=50), nullable=True),
    sa.Column('liquidation_status', sa.String(length=50), nullable=True),
    sa.Column('enforcement_status', sa.String(length=50), nullable=True),
    sa.Column('requisition_status', sa.String(length=50), nullable=True),
    sa.Column('budget_year', sa.Integer(), nullable=True),
    sa.Column('expected_payment_date', sa.Date(), nullable=True),
    sa.Column('legal_risk_level', sa.String(length=20), nullable=True),
    sa.Column('acquisition_eligibility', sa.String(length=30), nullable=True),
    sa.Column('acquisition_blockers', sa.JSON(), nullable=True),
    sa.Column('source_confidence', sa.String(length=20), nullable=True),
    sa.Column('validation_status', sa.String(length=30), nullable=False),
    sa.Column('pipeline_status', sa.Enum('PROCESSO_ENCONTRADO', 'POSSIVEL_CREDITO', 'ANALISE_AUTOMATICA', 'VALIDACAO_JURIDICA', 'ATIVO_QUALIFICADO', 'COMPRADORES_IDENTIFICADOS', 'TEASER_APROVADO', 'DISTRIBUIDO', 'INTERESSADO', 'EM_DILIGENCIA', 'PROPOSTA_RECEBIDA', 'NEGOCIACAO', 'AQUISICAO_CONCLUIDA', 'SEM_ATIVO', 'DESCARTADO', name='opportunitypipelinestatus', native_enum=False, length=30), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_judicial_opportunities_process_number'), 'judicial_opportunities', ['process_number'], unique=False)
    op.create_index(op.f('ix_judicial_opportunities_tenant_id'), 'judicial_opportunities', ['tenant_id'], unique=False)
    op.create_table('buyer_asset_matches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('opportunity_id', sa.String(length=36), nullable=False),
    sa.Column('buyer_profile_id', sa.String(length=36), nullable=False),
    sa.Column('compatibility_score', sa.Integer(), nullable=False),
    sa.Column('evaluated_weight', sa.Integer(), nullable=False),
    sa.Column('positive_reasons', sa.JSON(), nullable=True),
    sa.Column('negative_reasons', sa.JSON(), nullable=True),
    sa.Column('unverified_criteria', sa.JSON(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_profile_id'], ['buyer_profiles.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['judicial_opportunities.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opportunity_id', 'buyer_profile_id', name='uq_opportunity_buyer')
    )
    op.create_index(op.f('ix_buyer_asset_matches_buyer_profile_id'), 'buyer_asset_matches', ['buyer_profile_id'], unique=False)
    op.create_index(op.f('ix_buyer_asset_matches_opportunity_id'), 'buyer_asset_matches', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_buyer_asset_matches_tenant_id'), 'buyer_asset_matches', ['tenant_id'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('opportunity_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('RASCUNHO', 'PRONTA_PARA_REVISAO', 'APROVADA', 'ENVIANDO', 'CONCLUIDA', 'CANCELADA', name='campaignstatus', native_enum=False, length=30), nullable=False),
    sa.Column('teaser_text', sa.Text(), nullable=True),
    sa.Column('asking_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('asking_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('approved_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['judicial_opportunities.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_opportunity_id'), 'campaigns', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_campaigns_tenant_id'), 'campaigns', ['tenant_id'], unique=False)
    op.create_table('opportunity_field_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('opportunity_id', sa.String(length=36), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('source_excerpt', sa.Text(), nullable=True),
    sa.Column('source_document', sa.String(length=255), nullable=True),
    sa.Column('source_date', sa.Date(), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=True),
    sa.Column('extraction_method', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['judicial_opportunities.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunity_field_sources_opportunity_id'), 'opportunity_field_sources', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_opportunity_field_sources_tenant_id'), 'opportunity_field_sources', ['tenant_id'], unique=False)
    op.create_table('buyer_proposals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('opportunity_id', sa.String(length=36), nullable=False),
    sa.Column('buyer_profile_id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=True),
    sa.Column('proposal_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('proposal_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('asset_fraction', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('payment_terms', sa.Text(), nullable=True),
    sa.Column('conditions_precedent', sa.Text(), nullable=True),
    sa.Column('due_diligence_requirements', sa.Text(), nullable=True),
    sa.Column('exclusivity_requested', sa.Boolean(), nullable=False),
    sa.Column('proposal_expiration', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('RECEBIDA', 'EM_ANALISE', 'ACEITA', 'RECUSADA', 'EXPIRADA', 'RETIRADA', name='proposalstatus', native_enum=False, length=20), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('source_message_id', sa.String(length=255), nullable=True),
    sa.Column('entered_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_profile_id'], ['buyer_profiles.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['judicial_opportunities.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buyer_proposals_buyer_profile_id'), 'buyer_proposals', ['buyer_profile_id'], unique=False)
    op.create_index(op.f('ix_buyer_proposals_opportunity_id'), 'buyer_proposals', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_buyer_proposals_tenant_id'), 'buyer_proposals', ['tenant_id'], unique=False)
    op.create_table('campaign_recipients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('buyer_profile_id', sa.String(length=36), nullable=False),
    sa.Column('contact_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('RASCUNHO', 'PRONTO', 'ENVIADO', 'ENTREGUE', 'ABERTO', 'CLICADO', 'RESPONDIDO', 'BOUNCE', 'RECLAMACAO', 'DESCADASTRADO', 'ERRO', 'SUSPENSO', name='recipientstatus', native_enum=False, length=20), nullable=False),
    sa.Column('rendered_subject', sa.String(length=255), nullable=True),
    sa.Column('rendered_body', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_profile_id'], ['buyer_profiles.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_recipients_buyer_profile_id'), 'campaign_recipients', ['buyer_profile_id'], unique=False)
    op.create_index(op.f('ix_campaign_recipients_campaign_id'), 'campaign_recipients', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_recipients_tenant_id'), 'campaign_recipients', ['tenant_id'], unique=False)
    op.create_table('outbound_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_recipient_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['campaign_recipient_id'], ['campaign_recipients.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_outbound_messages_campaign_recipient_id'), 'outbound_messages', ['campaign_recipient_id'], unique=False)
    op.create_index(op.f('ix_outbound_messages_tenant_id'), 'outbound_messages', ['tenant_id'], unique=False)
    op.add_column('bot_jobs', sa.Column('tenant_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_bot_jobs_tenant_id'), 'bot_jobs', ['tenant_id'], unique=False)
    op.add_column('bot_steps', sa.Column('tenant_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_bot_steps_tenant_id'), 'bot_steps', ['tenant_id'], unique=False)
    op.add_column('certificate_records', sa.Column('tenant_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_certificate_records_tenant_id'), 'certificate_records', ['tenant_id'], unique=False)
    op.add_column('diligencia_logs', sa.Column('tenant_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_diligencia_logs_tenant_id'), 'diligencia_logs', ['tenant_id'], unique=False)
    op.add_column('intake_cases', sa.Column('tenant_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_intake_cases_tenant_id'), 'intake_cases', ['tenant_id'], unique=False)
    op.add_column('leads', sa.Column('tenant_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_leads_tenant_id'), 'leads', ['tenant_id'], unique=False)
    op.add_column('manual_evidences', sa.Column('tenant_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_manual_evidences_tenant_id'), 'manual_evidences', ['tenant_id'], unique=False)
    op.add_column('opportunity_leads', sa.Column('tenant_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_opportunity_leads_tenant_id'), 'opportunity_leads', ['tenant_id'], unique=False)
    op.add_column('process_results', sa.Column('tenant_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_process_results_tenant_id'), 'process_results', ['tenant_id'], unique=False)
    op.add_column('publication_hits', sa.Column('tenant_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_publication_hits_tenant_id'), 'publication_hits', ['tenant_id'], unique=False)
    op.add_column('search_logs', sa.Column('tenant_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_search_logs_tenant_id'), 'search_logs', ['tenant_id'], unique=False)
    op.add_column('stj_official_files', sa.Column('tenant_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_stj_official_files_tenant_id'), 'stj_official_files', ['tenant_id'], unique=False)
    op.add_column('watcher_runs', sa.Column('tenant_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_watcher_runs_tenant_id'), 'watcher_runs', ['tenant_id'], unique=False)
    op.add_column('whatsapp_messages', sa.Column('tenant_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_whatsapp_messages_tenant_id'), 'whatsapp_messages', ['tenant_id'], unique=False)
    # ### end Alembic commands ###

    # v36.1 — BACKFILL: todo registro legado (criado na v35, sem tenant)
    # precisa passar a pertencer a um tenant, senão o filtro por tenant
    # esconderia tudo. Cria o tenant padrão MeuPrecatórioBR (se não existir)
    # e associa TODOS os registros antigos a ele.
    import uuid as _uuid
    from datetime import datetime as _dt, timezone as _tz
    bind = op.get_bind()
    tenant_existente = bind.execute(sa.text("SELECT id FROM tenants WHERE slug = 'meuprecatoriobr'")).fetchone()
    if tenant_existente:
        tenant_id = tenant_existente[0]
    else:
        tenant_id = str(_uuid.uuid4())
        bind.execute(
            sa.text('INSERT INTO tenants (id, slug, nome, ativo, created_at) VALUES (:id, :slug, :nome, :ativo, :created_at)'),
            {'id': tenant_id, 'slug': 'meuprecatoriobr', 'nome': 'MeuPrecatórioBR', 'ativo': True, 'created_at': _dt.now(_tz.utc)},
        )
    for tabela in [
        'search_logs', 'process_results', 'certificate_records', 'manual_evidences',
        'diligencia_logs', 'bot_jobs', 'bot_steps', 'stj_official_files', 'leads',
        'whatsapp_messages', 'intake_cases', 'watcher_runs', 'publication_hits', 'opportunity_leads',
    ]:
        bind.execute(sa.text(f'UPDATE {tabela} SET tenant_id = :tid WHERE tenant_id IS NULL'), {'tid': tenant_id})
    # ### end backfill ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_whatsapp_messages_tenant_id'), table_name='whatsapp_messages')
    op.drop_column('whatsapp_messages', 'tenant_id')
    op.drop_index(op.f('ix_watcher_runs_tenant_id'), table_name='watcher_runs')
    op.drop_column('watcher_runs', 'tenant_id')
    op.drop_index(op.f('ix_stj_official_files_tenant_id'), table_name='stj_official_files')
    op.drop_column('stj_official_files', 'tenant_id')
    op.drop_index(op.f('ix_search_logs_tenant_id'), table_name='search_logs')
    op.drop_column('search_logs', 'tenant_id')
    op.drop_index(op.f('ix_publication_hits_tenant_id'), table_name='publication_hits')
    op.drop_column('publication_hits', 'tenant_id')
    op.drop_index(op.f('ix_process_results_tenant_id'), table_name='process_results')
    op.drop_column('process_results', 'tenant_id')
    op.drop_index(op.f('ix_opportunity_leads_tenant_id'), table_name='opportunity_leads')
    op.drop_column('opportunity_leads', 'tenant_id')
    op.drop_index(op.f('ix_manual_evidences_tenant_id'), table_name='manual_evidences')
    op.drop_column('manual_evidences', 'tenant_id')
    op.drop_index(op.f('ix_leads_tenant_id'), table_name='leads')
    op.drop_column('leads', 'tenant_id')
    op.drop_index(op.f('ix_intake_cases_tenant_id'), table_name='intake_cases')
    op.drop_column('intake_cases', 'tenant_id')
    op.drop_index(op.f('ix_diligencia_logs_tenant_id'), table_name='diligencia_logs')
    op.drop_column('diligencia_logs', 'tenant_id')
    op.drop_index(op.f('ix_certificate_records_tenant_id'), table_name='certificate_records')
    op.drop_column('certificate_records', 'tenant_id')
    op.drop_index(op.f('ix_bot_steps_tenant_id'), table_name='bot_steps')
    op.drop_column('bot_steps', 'tenant_id')
    op.drop_index(op.f('ix_bot_jobs_tenant_id'), table_name='bot_jobs')
    op.drop_column('bot_jobs', 'tenant_id')
    op.drop_index(op.f('ix_outbound_messages_tenant_id'), table_name='outbound_messages')
    op.drop_index(op.f('ix_outbound_messages_campaign_recipient_id'), table_name='outbound_messages')
    op.drop_table('outbound_messages')
    op.drop_index(op.f('ix_campaign_recipients_tenant_id'), table_name='campaign_recipients')
    op.drop_index(op.f('ix_campaign_recipients_campaign_id'), table_name='campaign_recipients')
    op.drop_index(op.f('ix_campaign_recipients_buyer_profile_id'), table_name='campaign_recipients')
    op.drop_table('campaign_recipients')
    op.drop_index(op.f('ix_buyer_proposals_tenant_id'), table_name='buyer_proposals')
    op.drop_index(op.f('ix_buyer_proposals_opportunity_id'), table_name='buyer_proposals')
    op.drop_index(op.f('ix_buyer_proposals_buyer_profile_id'), table_name='buyer_proposals')
    op.drop_table('buyer_proposals')
    op.drop_index(op.f('ix_opportunity_field_sources_tenant_id'), table_name='opportunity_field_sources')
    op.drop_index(op.f('ix_opportunity_field_sources_opportunity_id'), table_name='opportunity_field_sources')
    op.drop_table('opportunity_field_sources')
    op.drop_index(op.f('ix_campaigns_tenant_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_opportunity_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_buyer_asset_matches_tenant_id'), table_name='buyer_asset_matches')
    op.drop_index(op.f('ix_buyer_asset_matches_opportunity_id'), table_name='buyer_asset_matches')
    op.drop_index(op.f('ix_buyer_asset_matches_buyer_profile_id'), table_name='buyer_asset_matches')
    op.drop_table('buyer_asset_matches')
    op.drop_index(op.f('ix_judicial_opportunities_tenant_id'), table_name='judicial_opportunities')
    op.drop_index(op.f('ix_judicial_opportunities_process_number'), table_name='judicial_opportunities')
    op.drop_table('judicial_opportunities')
    op.drop_index(op.f('ix_contacts_tenant_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_person_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_buyer_mandates_tenant_id'), table_name='buyer_mandates')
    op.drop_index(op.f('ix_buyer_mandates_buyer_profile_id'), table_name='buyer_mandates')
    op.drop_table('buyer_mandates')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_token_hash'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_people_tenant_id'), table_name='people')
    op.drop_index(op.f('ix_people_organization_id'), table_name='people')
    op.drop_table('people')
    op.drop_index(op.f('ix_funds_tenant_id'), table_name='funds')
    op.drop_index(op.f('ix_funds_organization_id'), table_name='funds')
    op.drop_index(op.f('ix_funds_denom_social'), table_name='funds')
    op.drop_index(op.f('ix_funds_cnpj'), table_name='funds')
    op.drop_index(op.f('ix_funds_cd_cvm'), table_name='funds')
    op.drop_table('funds')
    op.drop_index(op.f('ix_buyer_profiles_tenant_id'), table_name='buyer_profiles')
    op.drop_index(op.f('ix_buyer_profiles_organization_id'), table_name='buyer_profiles')
    op.drop_table('buyer_profiles')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_suppression_list_tenant_id'), table_name='suppression_list')
    op.drop_index(op.f('ix_suppression_list_email'), table_name='suppression_list')
    op.drop_table('suppression_list')
    op.drop_index(op.f('ix_organizations_tenant_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_legal_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_cnpj'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_audit_log_entries_tenant_id'), table_name='audit_log_entries')
    op.drop_table('audit_log_entries')
    # ### end Alembic commands ###
